name: Tests

on:
  pull_request:
  push:
    branches: [stable]
  workflow_call:

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  python:
    uses: blacklanternsecurity/CLA/.github/workflows/python-tests.yml@40c6e18c0a6e32116eea4f89fc826f53c70889dc # main
    with:
      setup-script: scripts/build-openssl.sh
      env: '{"PYO3_USE_ABI3_FORWARD_COMPATIBILITY": "1"}'
