name: Tests

on:
  pull_request:
  push:
    branches: [stable]
  workflow_call:

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  python:
    uses: blacklanternsecurity/CLA/.github/workflows/python-tests.yml@de82726743e51ac51a1be31196d893312a9fea59 # main
    with:
      setup-script: scripts/build-openssl.sh
